/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/40k.glb --output components/Landing/Pintu/Door40k.tsx --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    tmp_i7lm6mfply: THREE.Mesh
  }
  materials: {}
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/40k.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.tmp_i7lm6mfply.geometry} material={nodes.tmp_i7lm6mfply.material} />
    </group>
  )
}

useGLTF.preload('/40k.glb')
