import { invitationCopyDefaults, parseEditableCopy, parseEnglishEditableCopy, type EditableInvitationCopy } from "@/lib/templates/editable-copy";
import { invitationTitleCase, weddingParentLine, type WeddingChildKind } from "@/lib/events/parents";

export type InvitationLanguage = "ID" | "EN";

/** Text owned by the invitation product. Event data and customer-authored copy are never machine-translated. */
const english: Record<string, string> = {
  "Sebuah Undangan Untuk Anda": "An Invitation For You",
  "Kami Mengundang Anda": "You Are Invited",
  "Sebuah hari untuk bertumbuh bersama.": "A day to grow together.",
  "Galeri Botani": "Botanical Gallery",
  "Tangkai Berbunga": "A Flowering Branch",
  "Pakis Muda": "A Young Fern",
  "Ilustrasi Sebelumnya": "Previous Illustration",
  "Ilustrasi Berikutnya": "Next Illustration",
  "Dengan hati yang hangat, kami mengundang Anda untuk merayakan satu hari yang istimewa.": "With warm hearts, we invite you to celebrate a special day.",
  "Kehadiran Anda akan melengkapi kebahagiaan yang kami rawat bersama.": "Your presence will enrich the joy we have nurtured together.",
  "Semoga kasih dan kebaikan senantiasa tumbuh dalam setiap langkah yang baru.": "May love and kindness grow with every new step.",
  "Terima kasih atas doa dan kehadiran yang membuat hari ini semakin berarti. Sampai bertemu.": "Thank you for your wishes and for making this day more meaningful with your presence. We look forward to seeing you.",
  "Pernikahan Kami": "Our Wedding",
  "Hari Istimewa": "A Special Day",
  "Pilih Foto": "Select Photo",
  "Buka Foto": "Open Photo",
  "Tutup Foto": "Close Photo",
  "Foto Sebelumnya": "Previous Photo",
  "Foto Berikutnya": "Next Photo",
  "Atur Foto Galeri": "Edit Gallery Photos",
  "Atur Foto Sampul": "Edit Cover Photo",
  "Di antara hari-hari yang datang dan pergi, ada satu yang ingin kami rayakan bersama Anda.": "Among the days that come and go, there is one we would love to celebrate with you.",
  "Kami mengundang Anda untuk berbagi waktu, cerita, dan kebahagiaan pada hari istimewa ini.": "We invite you to share in the moments, stories, and joy of this special day.",
  "Semoga langkah baru ini selalu dikelilingi kasih, kebaikan, dan doa yang tulus.": "May this new chapter be surrounded by love, kindness, and heartfelt wishes.",
  "Terima kasih untuk setiap doa dan kehadiran yang menghangatkan hari kami. Sampai bertemu.": "Thank you for every wish and for the presence that warms our day. We look forward to seeing you.",
  "Buka Undangan": "Open Invitation",
  "Musik": "Music",
  "Musik tidak tersedia": "Music unavailable",
  "Jeda musik undangan": "Pause invitation music",
  "Putar musik undangan": "Play invitation music",
  "Jeda musik": "Pause music",
  "Putar musik": "Play music",
  "Foto belum ditambahkan.": "No photos have been added yet.",
  "Setiap foto menyimpan cerita tentang kita.": "Every photo holds a story of us.",
  "Surat kecil untukmu": "A little letter for you",
  "Jalan kecil penuh cerita": "A little path full of stories",
  "Halaman-halaman kenangan": "Pages of memories",
  "Bunga-bunga yang mekar": "Flowers in bloom",
  "Perjalanan bersama": "A journey together",
  "Lampu jalan vintage": "A vintage streetlamp",
  "Sketsa pasangan": "A sketch of us",
  "Sepeda klasik": "A classic bicycle",
  "Kamera analog": "An analog camera",
  "Kaset nostalgia": "A nostalgic cassette",
  "Balon hati": "A heart balloon",
  "Tiket kenangan": "A ticket of memories",
  "Polaroid kisah kita": "A polaroid of our story",
  "Pita merah muda": "A pink ribbon",
  "Buku-buku lama": "Old books",
  "Sebuah Undangan": "An Invitation",
  "Untuk yang terkasih": "For our dear guests",
  "Untuk momen istimewa": "For a special moment",
  "Setiap cerita punya awalnya.": "Every story has a beginning.",
  "Sebuah undangan untuk orang istimewa": "An invitation for someone special",
  "Dua hati, satu cerita yang selalu tumbuh.": "Two hearts, one ever-growing story.",
  "Dua jiwa, satu perjalanan, menuju selamanya.": "Two souls, one journey, toward forever.",
  "Hari kita berdua": "Our Special Day",
  "Hari istimewa": "A Special Day",
  "Nama belum diisi": "Name not added",
  "Setiap pertemuan menyimpan cerita yang layak dikenang.": "Every meeting holds a story worth remembering.",
  "Kenangan indah hadir dalam setiap momen yang kita rayakan bersama.": "Beautiful memories live in every moment we celebrate together.",
  "Kehadiran Anda adalah bagian dari cerita kami.": "Your presence is part of our story.",
  "Dengan hangat kami mengundang Anda untuk merayakan hari istimewa kami.": "We warmly invite you to celebrate our special day.",
  "Undangan Pernikahan": "Wedding Invitation",
  "Perayaan Pernikahan": "Wedding Celebration",
  "Mempelai": "The Couple",
  "Mempelai pertama": "First Partner",
  "Mempelai kedua": "Second Partner",
  "Sampul": "Cover",
  "Dengan Hangat": "A Warm Welcome",
  "Dengan penuh sukacita": "With Joy",
  "Yang Mengundang": "Your Hosts",
  "Detail Acara": "Event Details",
  "Tanggal & Waktu": "Date & Time",
  "Galeri Foto": "Photo Gallery",
  "Galeri Cerita": "Our Moments",
  "Menuju Hari Bahagia": "Counting Down to Our Day",
  "Menuju Hari Istimewa": "Counting Down to the Day",
  "Hitung Mundur": "Countdown",
  "Lokasi": "Location",
  "Lokasi Acara": "Event Location",
  "Konfirmasi Kehadiran": "Confirm Attendance",
  "Ucapan & Doa": "Wishes & Prayers",
  "Tanda Kasih": "Gift",
  "Kirim Hadiah": "Send a Gift",
  "Terima Kasih": "Thank You",
  "Tentang Kami": "About Us",
  "Sebuah Cerita": "A Story",
  "Hari": "Days",
  "Jam": "Hours",
  "Menit": "Minutes",
  "Detik": "Seconds",
  "Tanggal belum ditentukan": "Date not set",
  "Tanggal acara belum tersedia.": "Event date is not available yet.",
  "Lokasi belum ditentukan": "Location not set",
  "Lihat Lokasi": "View Location",
  "Buka Google Maps": "Open Google Maps",
  "Tautan lokasi belum tersedia.": "Location link is not available yet.",
  "Belum ada foto galeri.": "No gallery photos yet.",
  "Foto galeri belum ditambahkan.": "No gallery photos have been added yet.",
  "Merupakan kebahagiaan bagi kami apabila Anda berkenan hadir.": "It would mean so much to us if you could join us.",
  "Informasi tanda kasih belum ditambahkan.": "Gift details are not available yet.",
  "Salin Nomor Rekening": "Copy Account Number",
  "Salin nomor rekening": "Copy account number",
  "Nomor rekening disalin.": "Account number copied.",
  "Belum dapat menyalin. Silakan salin nomor secara manual.": "Could not copy. Please copy the number manually.",
  "Mulai": "Starts",
  "Selesai": "Ends",
  "Selesai acara": "Event ends",
  "Untuk": "For",
  "Kuota undangan": "Invitation capacity",
  "orang, termasuk penerima.": "guests, including the recipient.",
  "Nama": "Name",
  "Nama lengkap": "Full name",
  "Nama kamu": "Your name",
  "No. WhatsApp": "WhatsApp number",
  "Acara yang akan dihadiri": "Events you will attend",
  "Pilih acara": "Select an event",
  "Upacara Nikah": "Wedding Ceremony",
  "Resepsi": "Reception",
  "Hadiri Semua Acara": "Attend All Events",
  "Status kehadiran": "Attendance status",
  "Saya Akan Hadir": "I Will Attend",
  "Saya Mungkin Hadir": "I Might Attend",
  "Saya Tidak Dapat Hadir": "I Cannot Attend",
  "Saya Tidak Hadir": "I Will Not Attend",
  "Saya Masih Tentatif": "I Am Not Sure Yet",
  "Jumlah pendamping": "Additional guests",
  "Ya": "Yes",
  "Tidak": "No",
  "Menyimpan...": "Saving...",
  "Kirim RSVP": "Send RSVP",
  "Konfirmasi hadir berhasil.": "Attendance confirmed.",
  "Konfirmasi kehadiran tersimpan.": "Your response has been saved.",
  "RSVP belum dapat disimpan.": "Could not save your RSVP.",
  "Koneksi bermasalah. Silakan coba lagi.": "Connection issue. Please try again.",
  "Kehadiran Anda telah berhasil dikonfirmasi. Kami menantikan kehadiran Anda di hari istimewa kami.": "Your attendance is confirmed. We look forward to seeing you on our special day.",
  "Konfirmasi Anda telah tersimpan. Terima kasih telah memberi kabar bahwa Anda belum dapat hadir.": "Your response is saved. Thank you for letting us know you cannot attend.",
  "Konfirmasi Anda telah tersimpan dengan status masih tentatif.": "Your tentative response has been saved.",
  "QR check-in tamu": "Guest check-in QR",
  "Unduh QR Code": "Download QR Code",
  "Simpan QR ini dan tunjukkan kepada petugas saat tiba di acara.": "Save this QR code and show it at check-in when you arrive.",
  "RSVP Anda sudah tersimpan. QR belum tersedia; hubungi pemilik undangan untuk bantuan.": "Your RSVP is saved. The QR code is unavailable; contact the host for help.",
  "Tambah ke Kalender": "Add to Calendar",
  "Isi nama dan ucapan (nama maks. 80 karakter, ucapan maks. 600 karakter).": "Enter your name and wish (up to 80 and 600 characters respectively).",
  "Ucapan berhasil dikirim. Terima kasih!": "Your wish was sent. Thank you!",
  "Ucapan belum dapat dimuat.": "Could not load wishes.",
  "Ucapan belum dapat dikirim.": "Could not send your wish.",
  "Tulis ucapan atau doa di sini…": "Write your wish or prayer here…",
  "Kirim Ucapan": "Send Wish",
  "Mengirim…": "Sending…",
  "Memuat ucapan…": "Loading wishes…",
  "Coba Lagi": "Try Again",
  "Belum ada ucapan. Jadilah yang pertama!": "No wishes yet. Be the first!",
  "Ucapan dari tamu": "Wishes from guests",
  "Our Story belum diisi": "Our Story has not been added",
  "WITH LOVE AND GRATITUDE": "WITH LOVE AND GRATITUDE",
  "Dengan penuh sukacita, kami berbagi kabar bahagia ini bersama Anda.": "With great joy, we share this happy news with you.",
  "Sebuah cerita kecil membawa kami menuju hari yang istimewa ini.": "A little story brought us to this special day.",
  "Dengan hati yang tenang, kami berbagi satu langkah penting dalam perjalanan kami.": "With grateful hearts, we share this meaningful step in our journey.",
  "Dengan senang hati, kami mengundang Anda untuk hadir dan merayakan hari istimewa ini bersama kami.": "We would be delighted to have you celebrate this special day with us.",
  "Kami berharap Anda berkenan hadir dan menjadi bagian dari perayaan kami.": "We hope you can join us and be part of our celebration.",
  "Merupakan kebahagiaan bagi kami apabila Anda berkenan hadir pada hari istimewa ini.": "It would bring us joy to have you with us on this special day.",
  "Kehadiran Anda akan menjadi bagian berarti dari perayaan ini.": "Your presence will make this celebration even more meaningful.",
  "Semoga hari ini menjadi awal dari perjalanan yang penuh kasih dan kebaikan.": "May this day begin a journey full of love and kindness.",
  "Doa dan harapan baik Anda kami terima dengan penuh syukur.": "We are grateful for your prayers and kind wishes.",
  "Doa dan harapan baik Anda menjadi hadiah yang kami syukuri.": "Your prayers and kind wishes are a gift we cherish.",
  "Terima kasih telah menjadi bagian dari cerita kami. Sampai bertemu!": "Thank you for being part of our story. See you soon!",
  "Atas doa, restu, dan kehadiran Anda dalam perjalanan istimewa ini.": "For your prayers, blessings, and presence on this special journey.",
  "Kehadiran dan doa baik Anda berarti bagi kami. Sampai bertemu di hari bahagia!": "Your presence and kind wishes mean so much to us. See you on our special day!",
  "Kehadiran dan doa baik Anda sangat berarti. Sampai bertemu!": "Your presence and kind wishes mean so much to us. See you soon!",
  "Cinta bukan tentang menemukan seseorang yang sempurna, tetapi tentang berjalan bersama dalam ketidaksempurnaan dengan hati yang tenang.": "Love is not about finding someone perfect, but walking together through imperfection with peaceful hearts.",
};

const indonesian: Record<string, string> = {
  "A personal invitation": "Undangan personal",
  "The Celebration": "Perayaan",
  "The celebration": "Perayaan",
  "A warm welcome": "Sambutan hangat",
  "Meet the hosts": "Kenali yang mengundang",
  "Our celebration": "Perayaan kami",
  "Save the date": "Catat tanggalnya",
  "Our moments": "Momen kami",
  "The day is near": "Hari istimewa kian dekat",
  "Your presence matters": "Kehadiran Anda berarti",
  "Kind words": "Ucapan penuh makna",
  "Until we meet": "Sampai bertemu",
  "Forever begins here": "Selamanya dimulai di sini",
  "Selected events": "Rangkaian acara",
  "In full bloom": "Mekar bersama",
  "A gilded celebration": "Perayaan berkilau",
  "Handcrafted in paper": "Dibuat dengan sepenuh hati",
  "Written in the stars": "Tertulis di bintang",
  "Every little moment matters.": "Setiap momen kecil berarti.",
  "A LITTLE STORY OF US": "SEBUAH CERITA TENTANG KAMI",
  "THE WEDDING OF": "PERNIKAHAN",
  "The Wedding Of": "Pernikahan",
  "The wedding invitation": "Undangan pernikahan",
  "The wedding of": "Pernikahan",
  "The two of us": "Kisah berdua",
  "A warm invitation": "Undangan hangat",
  "A day to remember": "Hari yang berkesan",
  "Our memories": "Kenangan kami",
  "Counting the moments": "Menghitung hari",
  "Find your way": "Temukan lokasinya",
  "Your presence means so much": "Kehadiran Anda berarti",
  "A little note of love": "Sepatah kata penuh kasih",
  "With gratitude": "Dengan rasa syukur",
  "Our Story": "Cerita kami",
};

export function invitationText(language: InvitationLanguage, text: string) {
  return language === "EN" ? english[text] ?? text : indonesian[text] ?? text;
}

export function localizedWeddingParentLine(language: InvitationLanguage, fatherName?: string | null, motherName?: string | null, childOrder?: number | null, kind: WeddingChildKind = "anak", position?: string | null) {
  if (language !== "EN") return weddingParentLine(fatherName, motherName, childOrder, kind, position);
  const parents = [fatherName?.trim() ? `Mr ${invitationTitleCase(fatherName.trim())}` : "", motherName?.trim() ? `Mrs ${invitationTitleCase(motherName.trim())}` : ""].filter(Boolean);
  if (!parents.length) return "";
  const order = position === "ELDEST" ? "eldest" : position === "YOUNGEST" ? "youngest" : childOrder && childOrder > 0 ? (() => {
    const suffix = childOrder % 100 >= 11 && childOrder % 100 <= 13 ? "th" : ({ 1: "st", 2: "nd", 3: "rd" } as Record<number, string>)[childOrder % 10] ?? "th";
    return `${childOrder}${suffix}`;
  })() : "";
  const child = kind === "putra" ? "Son" : kind === "putri" ? "Daughter" : "Child";
  return `${order ? `${invitationTitleCase(order)} ` : ""}${child} of ${parents.join(" & ")}`;
}

/** Translate only built-in defaults; preserve every customer edit and event description verbatim. */
export function localizedEditableCopy(designKey: string, templateKey: string, description: string | null | undefined, language: InvitationLanguage): EditableInvitationCopy {
  const defaults = invitationCopyDefaults(templateKey, description);
  const edits = parseEditableCopy(designKey);
  const copy = { ...defaults, ...edits };
  if (language !== "EN") return copy;
  const standardDefaults = invitationCopyDefaults(templateKey);
  for (const field of Object.keys(copy) as (keyof EditableInvitationCopy)[]) {
    if (copy[field] === standardDefaults[field] && copy[field]) copy[field] = invitationText(language, copy[field]);
  }
  return { ...copy, ...parseEnglishEditableCopy(designKey) };
}
