"use client";

import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type Invitation = { id:string; slug:string; title:string; groomName:string; brideName:string; templateKey:string; isPublished:boolean; owner:{id:string;email:string;firstName:string}; payment:{packageKey:string;status:string;amount:number}|null };
type User = { id:string;email:string;firstName:string;lastName:string|null;role:string;createdAt:string };

export default function AdminOperations(){
 const [users,setUsers]=useState<User[]>([]),[invitations,setInvitations]=useState<Invitation[]>([]),[selected,setSelected]=useState<Invitation|null>(null),[message,setMessage]=useState("Memuat database..."),[saving,setSaving]=useState(false);
 async function load(){const r=await fetch("/api/admin/operations",{cache:"no-store"});const d=await r.json();if(!r.ok){setMessage(d.error??"Database belum dapat dimuat.");return}setUsers(d.users??[]);setInvitations(d.invitations??[]);setMessage("")}
 useEffect(()=>{void load()},[]);
 async function save(){if(!selected)return;setSaving(true);const r=await fetch("/api/admin/operations",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({invitationId:selected.id,groomName:selected.groomName,brideName:selected.brideName})});const d=await r.json();setSaving(false);setMessage(r.ok?"Nama pengantin berhasil diperbarui.":d.error??"Perubahan gagal.");if(r.ok)await load()}
 async function publish(){if(!selected)return;setSaving(true);const r=await fetch("/api/admin/operations",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({invitationId:selected.id,action:"PUBLISH",isPublished:!selected.isPublished})});const d=await r.json();setSaving(false);setMessage(r.ok?(selected.isPublished?"Undangan dikembalikan ke draft.":"Undangan berhasil dipublish."):d.error??"Status publish gagal.");if(r.ok)await load()}
 return <section className="mx-auto max-w-6xl space-y-6 px-6 pb-10"><div className="grid gap-4 sm:grid-cols-3"><Metric label="Pengguna" value={users.length}/><Metric label="Undangan" value={invitations.length}/><Metric label="Published" value={invitations.filter(i=>i.isPublished).length}/></div><div className="grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><section className="rounded-2xl border border-black/10 bg-white p-5 dark:border-white/10 dark:bg-[#121116]"><h2 className="font-[family-name:var(--font-cinzel)] text-xl">Database user</h2><div className="mt-4 max-h-[420px] overflow-auto"><table className="w-full text-left text-sm"><thead className="border-b border-black/10 text-xs uppercase opacity-60 dark:border-white/10"><tr><th className="py-3">Nama</th><th className="py-3">Email</th><th className="py-3">Role</th></tr></thead><tbody>{users.map(u=><tr key={u.id} className="border-b border-black/5 dark:border-white/5"><td className="py-3">{u.firstName} {u.lastName??""}</td><td className="py-3 opacity-70">{u.email}</td><td className="py-3">{u.role}</td></tr>)}</tbody></table></div></section><section className="rounded-2xl border border-black/10 bg-white p-5 dark:border-white/10 dark:bg-[#121116]"><h2 className="font-[family-name:var(--font-cinzel)] text-xl">Bantuan data & publikasi</h2><select className="mt-4 h-10 w-full rounded-md border border-input bg-background px-3 text-sm" value={selected?.id??""} onChange={e=>setSelected(invitations.find(i=>i.id===e.target.value)??null)}><option value="">Pilih undangan</option>{invitations.map(i=><option key={i.id} value={i.id}>{i.groomName} & {i.brideName} · {i.owner.email}</option>)}</select>{selected&&<div className="mt-4 space-y-3"><Input value={selected.groomName} placeholder="Nama pengantin pria" onChange={e=>setSelected({...selected,groomName:e.target.value})}/><Input value={selected.brideName} placeholder="Nama pengantin wanita" onChange={e=>setSelected({...selected,brideName:e.target.value})}/><p className="text-xs opacity-60">Template: {selected.templateKey||"Belum dipilih"} · {selected.isPublished?"Published":"Draft"}</p><div className="grid gap-2 sm:grid-cols-2"><Button disabled={saving} onClick={save}>Simpan bantuan</Button><Button disabled={saving} onClick={publish}>{selected.isPublished?"Jadikan draft":"Publish untuk user"}</Button></div><a href={`/invite/${selected.slug}`} target="_blank" rel="noreferrer" className="block text-center text-xs text-[#C07A84] underline">Preview undangan user</a></div>}</section></div>{message&&<p className="rounded-xl bg-[#C07A84]/10 p-3 text-xs">{message}</p>}</section>
}
function Metric({label,value}:{label:string;value:number}){return <section className="rounded-2xl border border-black/10 bg-white p-5 dark:border-white/10 dark:bg-[#121116]"><p className="text-sm opacity-60">{label}</p><p className="mt-2 font-[family-name:var(--font-dm-mono)] text-3xl">{value}</p></section>}
